services:
  app:
    image: fastapi_tuiwen:0.3.0
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD", "python", "-c", "import httpx; response = httpx.get('http://localhost:8000/health-check/'); exit(1) if response.status_code != 200 else exit(0)"]
      interval: 30s
      timeout: 5s
      retries: 5
